# Generated by Django 5.1.2 on 2024-10-13 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['last_modified']},
        ),
    ]
